apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: default
data:
  appsettings.json: |
    {
      "loggingLevel": "verbose",
      "apiEndpoint": "http://api.example.com"
    }
