version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/postgresql/data

  flask:
    build: ./app
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # This line mounts a local file (nginx.conf) from your project directory into the container at the specified path (/etc/nginx/conf.d/default.conf).
      # This effectively replaces the default Nginx configuration file inside the container with your local version.
    depends_on:
      - flask

volumes:
  db-data:

# Open on port 80!
