FROM nginx:latest

# LABEL maintainer="you@example.com"

ENV NGINX_LOG_DIR /var/log/nginx
ENV LOG_LEVEL info
ENV DB_HOST localhost
ENV DB_PORT 5432

ENV FLASK_APP=app.py \
    FLASK_ENV=development \
    FLASK_DEBUG=1

COPY nginx.conf /etc/nginx/nginx.conf

VOLUME ["/var/log/nginx"]

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
