## SIMPLE SETUP
# services:
#   myapp:
#     image: myapp:latest
#     secrets:
#       - my_secret
# secrets:
#   my_secret:
#     file: ./my_secret.txt # should be created in the same folder as the docker-compose.yml file

# ADVANCED SETUP
services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_root_password
       - db_password

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_password


secrets:
   db_password:
     file: db_password.txt # should be created in the same folder as the docker-compose.yml file
   db_root_password:
     file: db_root_password.txt # should be created in the same folder as the docker-compose.yml file

volumes:
    db_data: