apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  # namespace: gk-namespace (OPTIONAL)
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: alpine-container
          image: alpine:latest
          command: ["tail", "-f", "/dev/null"]