# Manage external access to the services in a cluster, typically HTTP.
apiVersion: networking.k8s.io/v1  # Specifies the API version for ingress
kind: Ingress  # Defines the type of resource
metadata:
  name: my-ingress  # Name of the ingress
spec:
  rules:
  - host: myapp.example.com  # Hostname to which the ingress applies
    http:
      paths:
      - path: /  # Path that the rule applies to
        pathType: Prefix  # Type of path matching
        backend:
          service:
            name: my-service  # Name of the service to which traffic is directed
            port:
              number: 80  # Port of the service to use
