# Store and manage sensitive information, such as passwords, OAuth tokens, and ssh keys, protecting sensitive parts of your configuration.
apiVersion: v1  # Specifies the API version
kind: Secret  # Defines the type of resource
metadata:
  name: my-secret  # Name of the secret
type: Opaque  # Type of secret (Opaque is the default, indicating arbitrary user-defined data)
data:
  password: cGFzc3dvcmQ=  # Data stored as a base64-encoded string
  token: dG9rZW4=        # base64 encoded value of 'token'