version: '3.8'

services:

  mongo:
    image: mongo
    restart: always # ensures that the container keeps running unless it is explicitly stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # this is a volume
  
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # this is a bind-mount (a directory on the actual host)
      # This line mounts a local file (nginx.conf) from your project directory into the container at the specified path (/etc/nginx/conf.d/default.conf).
      # This effectively replaces the default Nginx configuration file inside the container with your local version.
    depends_on:
      - app

volumes:
  mongo-data:

# Open on port 3000!