apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: configmap-manager
  namespace: default
roleRef:
  kind: Role
  name: configmap-role
  apiGroup: rbac.authorization.k8s.io
